# Generated by Django 4.2.1 on 2023-05-09 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('quantidade', models.PositiveIntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tipo_operacao', models.CharField(choices=[('C', 'Compra'), ('V', 'Venda')], max_length=1)),
                ('corretagem', models.DecimalField(decimal_places=2, max_digits=8)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_wallet.investor')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_wallet.stock')),
            ],
        ),
    ]
